name: "Cro Koku Ryu"
description: "Nas klub"
paginate: 5
exclude: ["vendor"]
assets:
    js_compressor:  uglifier
    css_compressor: sass
    sources:
        - _assets/scripts
        - _assets/stylesheets
        - _assets/images
